defmodule SduiDemoWeb.Storybook.Components.CommentUI do
  @moduledoc """
  Story generated by AshSDUI.Storybook macro from the CommentUI standalone resource annotation.
  """

  use AshSDUI.Storybook, resource: SduiDemo.UI.Resources.CommentUI
end
