defmodule SduiDemoWeb.Storybook.Components.CommentUI do
  @moduledoc """
  Story generated by AshSDUI.Storybook macro from the CommentUI standalone resource annotation.
  """

  use AshSDUI.Storybook,
    ui: SduiDemo.UI.Resources.CommentUI,
    view: :show,
    bindings: %{
      record: %{
        id: "story-comment-1",
        body: "Storybook comment",
        posted_at: nil
      }
    }
end
