defmodule SduiDemoWeb.Storybook.Components.PostUI do
  @moduledoc """
  Story generated by AshSDUI.Storybook macro from the PostUI standalone resource annotation.

  Demonstrates the `use AshSDUI.Resource.Standalone` pattern for UI metadata.
  """

  use AshSDUI.Storybook, resource: SduiDemo.UI.Resources.PostUI
end
