defmodule SduiDemoWeb.Storybook.Components.UserUI do
  @moduledoc """
  Story generated by AshSDUI.Storybook macro from the UserUI standalone resource annotation.

  Demonstrates the `use AshSDUI.Resource.Standalone` pattern where UI metadata
  lives in a dedicated module instead of polluting the domain resource.
  """

  use AshSDUI.Storybook, resource: SduiDemo.UI.Resources.UserUI
end
