defmodule SduiDemoWeb.Storybook.Components.UserUI do
  @moduledoc """
  Story generated by AshSDUI.Storybook macro from the UserUI standalone resource annotation.

  Demonstrates the `use AshSDUI.Resource.Standalone` pattern where UI metadata
  lives in a dedicated module instead of polluting the domain resource.
  """

  use AshSDUI.Storybook,
    ui: SduiDemo.UI.Resources.UserUI,
    view: :show,
    bindings: %{
      record: %{
        id: "story-user-1",
        username: "storybook_user",
        email: "storybook@example.com",
        avatar_url: "https://example.com/avatar.png"
      }
    }
end
