defmodule SduiDemoWeb.Components.Layouts.PostFormPageLayout do
  @moduledoc """
  Page layout for post creation/editing — back button + form card.

  Attrs:
    - page_title: "New Post" | "Edit Post" (string)
    - form: AshPhoenix form object for native Phoenix form helpers
    - live_action: :new | :edit (atom)
    - post: nil (Post struct for edit mode)

  Note: Form is NOT an SDUI subject — it's a native Phoenix form. LiveView retains
  phx-change and phx-submit handlers. This component only renders the structure and styling.
  """

  use Phoenix.Component

  attr(:page_title, :string, required: true)
  attr(:form, :any, required: true)
  attr(:fields, :list, required: true)
  attr(:live_action, :atom, required: true)
  attr(:post, :any, default: nil)

  def render(assigns) do
    ~H"""
    <div class="mx-auto max-w-3xl space-y-6">
      <div class="space-y-3">
        <a href="/posts" class="btn btn-ghost btn-sm">Back to journal</a>
        <div class="space-y-2">
          <h1 class="text-3xl font-semibold text-base-content">{@page_title}</h1>
          <p class="max-w-2xl text-base-content/65">
            The form lifecycle stays generated by `AshSDUI.LiveResource`, while this page owns the surrounding editorial frame and a couple of app-specific fields.
          </p>
        </div>
      </div>

      <div class="card border border-base-300 bg-base-100 shadow-sm">
        <div class="card-body">
          <.resource_form
            form={@form}
            resource={SduiDemo.UI.Resources.PostUI}
            action={if(@live_action == :new, do: :create, else: :update)}
            fields={@fields}
            change_event="validate"
            submit_event="save"
            field_overrides={
              %{
                title: %{class: "h-15 text-3xl font-semibold tracking-normal"},
                body: %{class: "min-h-80 text-base leading-7"}
              }
            }
          >
            <:extra_fields :if={@live_action == :new}>
              <fieldset class="fieldset">
                <label class="label cursor-pointer justify-start gap-3">
                  <input
                    type="checkbox"
                    name="post[publish]"
                    value="true"
                    class="checkbox checkbox-primary"
                  />
                  <span class="label-text">Publish immediately</span>
                </label>
              </fieldset>
            </:extra_fields>
            <:extra_fields :if={@live_action == :edit && @post}>
              <div class="alert alert-info text-sm">
                <span>
                  Status:
                  <%= if @post.published_at do %>
                    <span class="badge badge-success badge-sm">
                      Published {Calendar.strftime(@post.published_at, "%b %d, %Y")}
                    </span>
                  <% else %>
                    <span class="badge badge-warning badge-sm">Draft</span>
                  <% end %>
                </span>
              </div>
            </:extra_fields>
            <:footer>
              <div class="flex justify-end gap-3 pt-2">
                <a href="/posts" class="btn btn-ghost">Cancel</a>
                <button type="submit" class="btn btn-primary">
                  {if @live_action == :new, do: "Create Post", else: "Save Changes"}
                </button>
              </div>
            </:footer>
          </.resource_form>
        </div>
      </div>
    </div>
    """
  end

  defp resource_form(assigns) do
    SduiDemoWeb.Components.ResourceForm.render(assigns)
  end
end
